update MD files
AccelerationConsortium/ac-microcourses pull request #52
Opened 2024-09-17 15:43 UTC by SissiFeng

2024-09-17 22:24 UTC, sgbaird requested changes

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +**Video Tutorial**: [Getting Started with VS Code](https://www.youtube.com/watch?v=VqCgcpAypFQ)
What do you think about this playlist instead? https://youtube.com/playlist?list=PLj6YeMhvp2S5UgiQnBfvD7XgOMKs3O_G6&si=W1bBOEPBcNSVn5KY

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +4. Ensure that VS Code is set up to use this environment for Python development.
This is probably a good place to link to official VS code docs related to conda environments

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +Miniconda is a lightweight distribution of Conda, an environment and package manager for Python. It allows you to manage multiple isolated environments on your machine.
It might be worth making a ```note ``` about mamba which is a much faster version of conda with the same functionality

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +- [GitHub Copilot](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot): An AI-powered coding assistant.
It would be good to add the GitHub copilot chat extension

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +2. Set up SSH on your local machine by generating SSH keys:
I'm actually a bit confused here on the example it's being shown. Is the idea that your SSHing from your own machine to some other part of your machine? I wonder if there's another way to show the use of SSH relative to another platform, or at least point out an example. In my case I've used this extension a lot in the context of University high performance compute clusters and submitting SLURM jobs.

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +**Video Tutorial**: [VS Code Remote Development with SSH](https://www.youtube.com/watch?v=miyD4c1dnTU&pp=ygUjVlMgQ29kZSBSZW1vdGUgRGV2ZWxvcG1lbnQgd2l0aCBTU0g%3D)
This video seems pretty reasonable. While I didn't watch it in full, it looks fairly recent and has a decent number of views and likes. It would be best for possible for at least one of us to watch a video in full before linking out to it. In general it's best to find videos that are from an official source, but I don't think there would be for this one. That may often be the case. Sometimes the non-official videos are better too.

2024-09-17 22:24 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +### Configuring Black Formatter
I still need to finish my review, but I'll come back to this

2024-09-19 14:04 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +**Video Tutorial**: [Getting Started with VS Code](https://www.youtube.com/watch?v=VqCgcpAypFQ)
Feedback: original one is more beginner friendly

2024-09-19 14:17 UTC, sgbaird commented on docs/courses/software-dev/4.1-vscode-setup.md
> +2. Set up SSH on your local machine by generating SSH keys:
Usecase: Raspberry Pi ssh with VS Code extension. I'll get you an RPi 5 and a screen. Maybe mention HPC as a common example in physical sciences

2024-10-07 14:56 UTC, SissiFeng commented
> I forget if it was this one or the other PR that I still couldn't compile the docs with. I was able to for some of the other PRs though

I will integrate your changes from this PR into the original document and then open a new PR.

2024-10-09 15:12 UTC, sgbaird approved these changes

2024-10-09 15:13 UTC, merged